# version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app/frontend
      - frontend_node_modules:/app/frontend/node_modules
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    # profiles:
    #   - local

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    # profiles:
    #   - local

  mysql:
    image: mysql:8.0
    container_name: 204prod-database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    # profiles:
    #   - local

volumes:
  mysql_data:
  frontend_node_modules:
