"""extend_client_fields

Revision ID: 24a4aa54a7ae
Revises: c54e654587eb
Create Date: 2026-05-25 16:05:47.074740
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '24a4aa54a7ae'
down_revision: str | None = 'c54e654587eb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('contact', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('phone', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('industry', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('clients', sa.Column('since', sa.String(length=10), nullable=True))
    op.add_column('clients', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'notes')
    op.drop_column('clients', 'since')
    op.drop_column('clients', 'status')
    op.drop_column('clients', 'industry')
    op.drop_column('clients', 'phone')
    op.drop_column('clients', 'email')
    op.drop_column('clients', 'contact')
    # ### end Alembic commands ###
