"""add_project_activities_and_comments

Revision ID: 289bd770646a
Revises: 095f62c4b59f
Create Date: 2026-07-08 08:17:12.605785
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '289bd770646a'
down_revision: str | None = '095f62c4b59f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
