"""Add GDrive Albums

Revision ID: 34b19a0b6ec1
Revises: d91a823b7e45
Create Date: 2026-07-29 16:27:54.380518
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '34b19a0b6ec1'
down_revision: str | None = 'd91a823b7e45'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_feedbacks', 'guest_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=180),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_feedbacks', 'guest_name',
               existing_type=sa.String(length=180),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
