"""add video_url to project_feedbacks

Revision ID: 43eab67fe4f6
Revises: a9bfb3e23d0c
Create Date: 2026-07-03 05:51:47.584564
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '43eab67fe4f6'
down_revision: str | None = 'a9bfb3e23d0c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_client_slug'), table_name='client_invoices')
    op.create_index(op.f('ix_client_invoices_client_slug'), 'client_invoices', ['client_slug'], unique=False)
    op.create_index(op.f('ix_client_invoices_id'), 'client_invoices', ['id'], unique=False)
    op.add_column('project_feedbacks', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_project_feedbacks_video_url'), 'project_feedbacks', ['video_url'], unique=False)
    op.alter_column('project_gallery_images', 'published',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_gallery_images', 'published',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.drop_index(op.f('ix_project_feedbacks_video_url'), table_name='project_feedbacks')
    op.drop_column('project_feedbacks', 'video_url')
    op.drop_index(op.f('ix_client_invoices_id'), table_name='client_invoices')
    op.drop_index(op.f('ix_client_invoices_client_slug'), table_name='client_invoices')
    op.create_index(op.f('idx_client_slug'), 'client_invoices', ['client_slug'], unique=False)
    # ### end Alembic commands ###
