"""Add messaging models

Revision ID: 54e39202ed8c
Revises: ba5911644343
Create Date: 2026-07-23 03:10:37.610479
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '54e39202ed8c'
down_revision: str | None = 'ba5911644343'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
