"""add reply fields to feedback

Revision ID: 5f1ee63386bc
Revises: fbd664d35957
Create Date: 2026-06-24 08:08:54.338991
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5f1ee63386bc'
down_revision: str | None = 'fbd664d35957'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_feedbacks', sa.Column('reply_content', sa.Text(), nullable=True))
    op.add_column('project_feedbacks', sa.Column('reply_author', sa.String(length=100), nullable=True))
    op.add_column('project_feedbacks', sa.Column('reply_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_feedbacks', 'reply_at')
    op.drop_column('project_feedbacks', 'reply_author')
    op.drop_column('project_feedbacks', 'reply_content')
    # ### end Alembic commands ###
