"""add_publish_and_lock_to_projects

Revision ID: 733d85902ef5
Revises: 324ae9b804c5
Create Date: 2026-06-29 00:17:25.363438
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '733d85902ef5'
down_revision: str | None = '324ae9b804c5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('published', sa.Boolean(), nullable=False))
    op.add_column('projects', sa.Column('locked', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_projects_locked'), 'projects', ['locked'], unique=False)
    op.create_index(op.f('ix_projects_published'), 'projects', ['published'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_published'), table_name='projects')
    op.drop_index(op.f('ix_projects_locked'), table_name='projects')
    op.drop_column('projects', 'locked')
    op.drop_column('projects', 'published')
    # ### end Alembic commands ###
