"""add_client_project_folder_to_media

Revision ID: a9bfb3e23d0c
Revises: e6e226bf3f19
Create Date: 2026-07-01 08:28:06.632240
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a9bfb3e23d0c'
down_revision: str | None = 'e6e226bf3f19'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_assets', sa.Column('client_slug', sa.String(length=120), nullable=True))
    op.add_column('media_assets', sa.Column('project_slug', sa.String(length=160), nullable=True))
    op.add_column('media_assets', sa.Column('folder', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'media_assets', 'projects', ['project_slug'], ['slug'], ondelete='SET NULL')
    op.create_foreign_key(None, 'media_assets', 'clients', ['client_slug'], ['slug'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media_assets', type_='foreignkey')
    op.drop_constraint(None, 'media_assets', type_='foreignkey')
    op.drop_column('media_assets', 'folder')
    op.drop_column('media_assets', 'project_slug')
    op.drop_column('media_assets', 'client_slug')
    # ### end Alembic commands ###
