"""Add crew_id to project credits

Revision ID: ba5911644343
Revises: c71211571f73
Create Date: 2026-07-13 07:02:05.007522
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'ba5911644343'
down_revision: str | None = 'c71211571f73'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_credits', sa.Column('crew_id', sa.Integer(), nullable=True))
    op.add_column('project_gallery_images', sa.Column('crew_id', sa.Integer(), nullable=True))
    op.alter_column('project_tasks', 'assignee_name',
               existing_type=mysql.VARCHAR(length=180),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('project_tasks', 'assignee_initials',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_tasks', 'assignee_initials',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('project_tasks', 'assignee_name',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=180),
               existing_nullable=True)
    op.drop_column('project_gallery_images', 'crew_id')
    op.drop_column('project_credits', 'crew_id')
    # ### end Alembic commands ###
