"""Add poll votes and message metadata

Revision ID: c244031c2a98
Revises: c41787d8a4e5
Create Date: 2026-07-23 15:48:07.067582
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c244031c2a98'
down_revision: str | None = 'c41787d8a4e5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Table already exists due to Base.metadata.create_all
    op.add_column('messaging_messages', sa.Column('message_type', sa.String(length=50), nullable=False))
    op.add_column('messaging_messages', sa.Column('metadata_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messaging_messages', 'metadata_json')
    op.drop_column('messaging_messages', 'message_type')
    op.drop_index(op.f('ix_messaging_poll_votes_user_id'), table_name='messaging_poll_votes')
    op.drop_index(op.f('ix_messaging_poll_votes_message_id'), table_name='messaging_poll_votes')
    op.drop_index(op.f('ix_messaging_poll_votes_id'), table_name='messaging_poll_votes')
    op.drop_table('messaging_poll_votes')
    # ### end Alembic commands ###
