"""add_avatar_url_to_conversation

Revision ID: c41787d8a4e5
Revises: 54e39202ed8c
Create Date: 2026-07-23 15:10:09.056242
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c41787d8a4e5'
down_revision: str | None = '54e39202ed8c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


from sqlalchemy.engine.reflection import Inspector

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    columns = [c['name'] for c in inspector.get_columns('messaging_conversations')]
    if 'avatar_url' not in columns:
        op.add_column('messaging_conversations', sa.Column('avatar_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messaging_conversations', 'avatar_url')
    # ### end Alembic commands ###
