"""add_video_url_to_projects

Revision ID: c54e654587eb
Revises: 0001_create_admin_schema
Create Date: 2026-05-25 15:47:42.658561
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'c54e654587eb'
down_revision: str | None = '0001_create_admin_schema'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crew_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('skills_expertise', sa.String(length=500), nullable=True),
    sa.Column('assigned_projects', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crew_members_id'), 'crew_members', ['id'], unique=False)
    op.alter_column('categories', 'description',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.add_column('projects', sa.Column('video_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'video_url')
    op.alter_column('categories', 'description',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_crew_members_id'), table_name='crew_members')
    op.drop_table('crew_members')
    # ### end Alembic commands ###
