"""Add work_mode to CrewMember

Revision ID: c71211571f73
Revises: 289bd770646a
Create Date: 2026-07-08 16:38:29.407538
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c71211571f73'
down_revision: str | None = '289bd770646a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crew_members', sa.Column('work_mode', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crew_members', 'work_mode')
    # ### end Alembic commands ###
