"""add_kanban_tasks

Revision ID: cf9401f8212b
Revises: 733d85902ef5
Create Date: 2026-06-30 04:43:47.381163
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'cf9401f8212b'
down_revision: str | None = '733d85902ef5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
