"""add_slug_to_media

Revision ID: d3c26dd9ef2d
Revises: d00000000001
Create Date: 2026-08-11 16:16:49.170235
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd3c26dd9ef2d'
down_revision: str | None = 'd00000000001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_assets', sa.Column('slug', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_media_assets_slug'), 'media_assets', ['slug'], unique=True)
    op.add_column('media_folders', sa.Column('slug', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_media_folders_slug'), 'media_folders', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_folders_slug'), table_name='media_folders')
    op.drop_column('media_folders', 'slug')
    op.drop_index(op.f('ix_media_assets_slug'), table_name='media_assets')
    op.drop_column('media_assets', 'slug')
    # ### end Alembic commands ###
