"""Add bunny_video_id

Revision ID: e6e226bf3f19
Revises: 81252a9f3f9e
Create Date: 2026-07-01 06:44:21.437935
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e6e226bf3f19'
down_revision: str | None = '81252a9f3f9e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_assets', sa.Column('bunny_video_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_assets', 'bunny_video_id')
    # ### end Alembic commands ###
