"""create feedback model

Revision ID: fbd664d35957
Revises: 24a4aa54a7ae
Create Date: 2026-06-24 07:20:46.319035
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'fbd664d35957'
down_revision: str | None = '24a4aa54a7ae'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_slug', sa.String(length=160), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('timecode', sa.Float(), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_slug'], ['projects.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_feedbacks_project_slug'), 'project_feedbacks', ['project_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_feedbacks_project_slug'), table_name='project_feedbacks')
    op.drop_table('project_feedbacks')
    # ### end Alembic commands ###
